# Generated by Django 4.0.5 on 2022-06-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20220322_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='RecipyfindLogo.png', null=True, upload_to='', verbose_name='RecipyFindLogo')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.IntegerField(default=0, verbose_name='Preparation time in minutes'),
        ),
    ]
